firefox:
  desktop:
    desktop_browser: &desktop
      width: 1300
      height: 1000
      browser: firefox
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A'
  mobile:
    mobile_browser: &mobile
      <<: *desktop
      width: 300
      height: 640
      user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'
  tablet:
    tablet_browser: &tablet
      <<: *desktop
      width: 768
      height: 1024
      user_agent: 'Mozilla/5.0 Tablet(Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19'
chrome:
  desktop:
    desktop_browser:
     <<: *desktop
  mobile:
    mobile_browser:
      <<: *mobile
  tablet:
    tablet_browser:
      <<: *tablet